version: '3.9'

services:
  toxic-classifier:
    command: python3 main.py
    image: kaungnyo/nlp-a7:v001
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    volumes:
      - ./app:/root/app
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80

